---
title: "Project 1 - Avengers"
author: "Ye Dam Yi"
date: "2/16/2021"
output: html_document
---

```{r}
library(tidyverse)
```

```{r data-import}
avengers <- read_csv("/Users/yedam/Documents/GitHub/DSP/Project/538-data/avengers/avengers.csv")
```

```{r insepct-data}
names(avengers)
glimpse(avengers)
```

```{r mortality, fig.height=5, fig.width=6}
# create color blind friendly palette
# The palette with grey:
cb.palette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

# What's the mortality rate of the Avengers? 
avengers %>% 
  ggplot(mapping = aes(x = Death1)) +
  geom_bar(fill="#E69F00", colour="black") +
  coord_flip() +
  labs(x = "Death",
       y = "Number of Deaths",
       title = "Mortality of the Avengers") 


```

```{r gender-mortality}

#What's the mortality rate of the Avengers by gender?
avengers %>% 
ggplot(mapping = aes(x = Gender, fill = Death1)) +
  geom_bar(colour="black", position = "fill") +
  coord_flip() +
  labs(x = "Death",
       y = "Gender",
       title = "Mortality of the Avengers",
       subtitle = "By gender") + 
    scale_fill_manual(values=cb.palette)


```

```[r ]